### ISSUE TITLE
Run the bridge validators nodes

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#10]
Run two bridge validators nodes.

**Comment by saschagoebel** [comment]
See https://github.com/trustlines-protocol/blockchain/issues/9

**Comment by jannikluhn** [comment]
I tried to follow the `docker-compose` approach to run a bridge validator, but it didn't work. Opened an issue here: https://github.com/poanetwork/token-bridge/issues/142

**Comment by jannikluhn** [comment]
The problem with `docker-compose` supposedly is that the launched docker instances can't communicate with the Parity instances because they expose their RPC interface to the host. So the connection would be `Docker -> Host -> Docker` which is apparently not allowed.

Therefore, I've created three new Docker networks (one for each node) and added the Parity nodes as well as all relevant bridge containers. However, the problem still persists, but I think it's because I've failed to set up the network correctly.

To reproduce the issue, I setup a completely separate network as well as two new "alpine" containers following the [documentation](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks). The containers are running and are connected to the network (according to `docker network inspect`). I can ping each of them from the host by IP. However, pinging between the containers from within doesn't work (neither by IP nor by container name):

```
/ # ping -c 2 alpine2
PING alpine2 (192.168.224.3): 56 data bytes

--- alpine2 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```

I'm stuck. Can someone with more Docker experience have a look please? @thore maybe?

**Comment by weilbith** [comment]
@jannikluhn I remember that I have had some issues into the same direction a you. I'm a bit confused by your description and I think writing in the comments here only will not workout. Can you provide a small enough example setup to share with my that I can test on my own. Else I would contract you tomorrow per call if that is okay for you. Nevertheless this could be very tricky with Docker I know.

**Comment by jannikluhn** [comment]
Here are the commands I used for the minimal reproduction of the problem:

```
docker network create --driver bridge alpine-net
docker run -dit --name alpine1 --network alpine-net alpine ash
docker run -dit --name alpine2 --network alpine-net alpine ash
docker container attach alpine1
ping alpine2 # in the container
```

result:
```
/ # ping alpine2
PING alpine2 (192.168.224.3): 56 data bytes
^C
--- alpine2 ping statistics ---
61 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by weilbith** [comment]
@jannikluhn bad news: works without problems on my local machine as well as on my home server and also a DO instance as you are using. So I probably need access to that machine to clarify the problem or you should just use another environment.

**Comment by weilbith** [comment]
The Docker network with the bridge is using an awkward IP range. It is using the `192.168.` range (actually reserved for local network purpose) with `.240.` as third byte. The typical prefix for Docker bridges is `172.18.0.x`. This DO instance is the only one I observe this behavior.

**Comment by weilbith** [comment]
"Fixed" the awkward bridge range. Still not working between the containers.

**Comment by weilbith** [comment]
@jannikluhn it is working now. Not much important details to share here.

**Comment by jannikluhn** [comment]
two bridge validator nodes are running

**Comment by weilbith** [comment]
The setup has been presented with a working performance. Therefore I consider this issues as done.
