### ISSUE TITLE
Write theoretical doc of how the auction works

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#167]
Not practical documentation, no screenshots ...

**Comment by jannikluhn** [comment]
Probably wrong on some details and I may have missed some things, but here's a rough first draft:

- The auction is a smart contract on the Ethereum main chain at address ?
- The auction is started with a transaction to be sent by ? at a specific point in time
- The auction defines a price that starts at x and continuously and automatically decreases over time during the course of the auction.
- To be able to participate in the auction, one's Ethereum address must be whitelisted by ? prior to the start of the auction
- Every whitelisted Ethereum account can participate in the auction exactly once.
- To participate in the auction, a whitelisted Ethereum account has to send ETH to the auction contract after it has started and before it has ended. The amount must be greater or equal to the current price.
- The auction ends at latest when the price reaches ? or the 123rd bid is accounted, whatever comes first.
- If fewer than 50 accounts have participated at the time the auction ends, it is deemed a failure, otherwise a success.
- If the auction has failed, all participants can withdraw their sent ETH by calling the auction contract's `withdraw` function.
- If the auction is successful, we define the slot price as the price of the last bid. Every participant can withdraw the difference between the slot price and their bid by calling the `withdraw` function
- If the auction is successful, the ETH that can not be withdrawn will be transferred to the deposit locker contract and the participating account addresses will be communicated to it.

(I've got to admit that it's more than 5 sentences)

**Comment by cducrest** [comment]
I correct some and remove what I believe is not useful:

- The auction is a smart contract on the Ethereum main chain
- The auction is started with a transaction to be sent by the Trustlines Foundation at a the provisioned start date
- The auction defines a price starting at 10,000 ETH that continuously decreases over time during the course of the auction. The price will reach 1 ETH after two weeks.
- To be able to participate in the auction, one's Ethereum address must be whitelisted by the Trustlines Foundation prior to the start of the auction
- Every whitelisted Ethereum account can participate in the auction exactly once
- To participate in the auction, a whitelisted Ethereum address has to send ETH to the auction contract after it has started and before it has ended. The amount must be greater or equal to the current price.
- The auction ends at the latest after two weeks or when the 123rd bid is accounted, whichever comes first.
- If fewer than 50 accounts have participated at the time the auction ends, it is deemed a failure, otherwise it is a success.
- If the auction has failed, all participants can withdraw the entirety of the ETH  they sent by calling the auction contract's `withdraw` function. Participants will not be granted the status of validator on the Trustlines chain
- If the auction is successful, we define the slot price as the price of the last bid. Every participant can withdraw the difference between the slot price and their bid by calling the `withdraw` function. Participants will be granted the status of validator on the Trustlines chain
- If the auction is successful, the ETH that can not be withdrawn will be transferred to the deposit locker contract and kept there as stake for 9 months.

Tell me what you think about it Jannik

**Comment by jannikluhn** [comment]
LGTM

**Comment by jannikluhn** [comment]
Copied to a google doc: https://docs.google.com/document/d/1bnmm0DmZYDmEKQyGoesGKGgJqQXXl8yCfvrFF53lr3I/edit#heading=h.q01h589jzkcm

**Comment by jannikluhn** [comment]
Transformed bullet points -> prose (mostly by removing line breaks). Also, very slight changes to the content, but nothing noteworthy I think.

**Comment by cducrest** [comment]
LGTM
