### ISSUE TITLE
Bridge client address logging type problem

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#269]
The addresses provided in the bridge client unit tests are of type `str` due to the `contract-deploy-tools`. But the `config` module converts addresses to `bytes`. Thereby for the production mode the addresses in logging/error messages look weird since they are represented as bytes. Same goes for the event fetcher log name. Thereby it would be useful to apply `.hex()` to each place printing a bytes address. But this would lead to exceptions during the unit tests, cause the String types addresses do not have such property.
Therefore we should rethink which type of address we want to return within the configuration module. Else we need to convert addresses to their byte representation at any part of the tests and mind to convert them back also. Alternatively we could use the String representation in the whole client. This has worked already in the past and still do.

**Comment by weilbith** [comment]
@jannikluhn you introduced the conversion to bytes. What is the benefit after the `isChecksumAddress()` verification? :thinking:

**Comment by jannikluhn** [comment]
I like bytes because it's the easiest format to follow consistently. Hex is not unique (upper/lower case, `0x` prefixed or not). Checksum might or might not be unique (not sure about the prefix here), but not consistent with other binary data (private keys, public keys, hashes). Also, to me checksum addresses are a user interface thing, using them internally feels backwards.

Being able to print them directly is nice of course. But I don't think it's worth the tradeoff.

> Thereby it would be useful to apply .hex() to each place printing a bytes address.

We can just use `eth_utils.to_checksum_address` or `eth_utils.to_hex_address` which works with all kinds of input formats.

Also, I don't know the full context to this issue, but if I understood correctly it arises when accessing `contract.address` after instantiating the contract with different types of input formats. I'd argue that this is actually a bug in web3: They may allow different formats to be used, but should convert them immediately to one they follow consistently (ideally, bytes, see above).

**Comment by weilbith** [comment]
This problem is solved with PR #268. Since I don't expect this PR to be rejected I close this issue.
