### ISSUE TITLE
bridge: Exception handling in prepare_confirmation_transaction looks fishy

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#279]
The [prepare_confirmation_transaction method](https://github.com/trustlines-protocol/blockchain/blob/a3a8da781f2a0ead1b0cc9e7c71ba530e49dacfb/tools/bridge/bridge/confirmation_sender.py#L79) catches a ValueError with the following code:
```     
        try:
            ...
        except ValueError as e:
            if "failed due to an exception" in e.args[0]["message"]:
                self.logger.info(
```

If the try block raises a `ValueError` with something like `raise ValueErrror("foo")`, the catch block would  throw a `TypeError: string indices must be integers`.

The code in question was introduced in 3bdb7ede0bb80cff90e812dd1e1e73b3054c5a03

My guess is this error we're trying to catch is raised in `buildTransaction`, so we should move the other code out of the try block.

Also, the test 'failed due to an exception' in error message looks very generic. I fear this may match more exceptions than we actually want.

**Comment by schmir-at-bb** [comment]
@saschagoebel Any comments on this one? I guess you did actually test this with a running program, right?

**Comment by saschagoebel** [comment]
Yes, this was part of the docker compose task, so it ran on a real chain with a deployed contract.

I was not able to find any better error message in this case, because the transaction is never actually executed, so there's no stack trace either.

I found some StackOverflow posts and issues with similar questions, but no usable answer.

If you come up with something that gives us the actual error, I'd be happy to change it.

I left the signing in the try block, because I want execution to stop at this point in any case. But I've heard rumors that exceptions in python are used differently though.

**Comment by schmir-at-bb** [comment]
Thanks for the clarification. We should at least clean that up a bit and add some clarifying comments.

**Comment by jannikluhn** [comment]
Closing as we don't handle this error anymore (we specify the gas limit explicitly now, so the error shouldn't ever be thrown).

**Comment by schmir-at-bb** [comment]
This has been removed in d000a668e5990edbddd71539867280a4fa599f67.
