### ISSUE TITLE
Release docker image for bridge

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#301]
Build Docker Image on circleci and upload it to dockerhub. We should probably use the same setup as for the tlbc-testnet (i.e. not allow everyone to make a new release and require approval)
We should also be able to release the bridge without releasing a new tlbc-testnet release (i.e. we will probably use a different branch than the branch we use for tlbc-testnet) and vice-versa

**Comment by weilbith** [comment]
The `Dockerfile` does already exist. @schmir-at-bb handles the `tlbc-testnet` image at the moment if I'm correct. What do we need for this issues except pushing a build image?

**Comment by berndbohmeier** [comment]
I dont know what you mean by ralf handles the testnet image. 
We have to write the code for circle ci to build and upload it. You can look at the existing code for the tlbc image and have a chat with Ralf on how to solve that we can release them independently.

**Comment by weilbith** [comment]
**Question:**
On which branches should the new _Docker_ image be published to _DockerHub_?
The `quickstart` as well as the `tlbc-testnet-next` images do so for `master` and `pre-release`.  The "production" image `tlbc-testnet` image only gets tagged and published on the `release` branch.

I have now a version which build and publishes the `tlbc-bridge-validator` image when pushing to the new proposed `release-bridge-validator` branch (super creative I know). I'm not sure how much sense this makes, but do we like to have a version which also deploys on `master`? `pre-release` is related to the `release` branch of the `tlbc-testnet` image. Since the build should be independent, the `tlbc-bridge-validator` should be not listen on this branch. Having a `pre-release-bridge-validator` branch does not make sense to me, since there is nothing to present and agree on with externals. Doesn't it?

**Comment by schmir-at-bb** [comment]
I would create two branches bridge/pre-release and bridge/release and upload from master and those two branches.

master -> bridge-next:master
bridge/pre-release -> bridge-next:pre-release
bridge/release -> bridge:latest

I would not use the validator suffix.

**Comment by weilbith** [comment]
> I would not use the validator suffix.

I called it like this, because other targets are also named so (e.g. `mypy-bridge-validator`) and because I think some additional specificity can't be bad here. But this is not important and I remove it during the additions. :smiley:

**Comment by weilbith** [comment]
Okay I have extended if for Ralf his suggested branch to image name/tag mapping.
I gave up to make it pretty. The only really new part is the cleaning of the branch name since we use now the prefix for the releases. 
Anyways @schmir-at-bb do we want to have an image comparison before a release of the bridge image as we do for the Parity one? I don't remember the origin background of this and thereby I'm not sure if this is a use-case here.

**Comment by weilbith** [comment]
Moreover I think we should adjust the docker compose files. They are currently building the image on their own. I'm thinking what the best solution could be.

**Comment by weilbith** [comment]
Input from recent meeting: yes image comparison is a nice to have and will be added.

**Comment by schmir-at-bb** [comment]
> Input from recent meeting: yes image comparison is a nice to have and will be added.



> Moreover I think we should adjust the docker compose files. They are currently building the image on their own. I'm thinking what the best solution could be.

docker-compose conflates things that are quite separate (run and build). 

We can always build locally before running docker-compose.

I think there should be a good reason if we build from the docker-compose file. I don't see a good reason if we have the image on dockerhub.

**Comment by schmir-at-bb** [comment]
but maybe @saschagoebel has one?

**Comment by saschagoebel** [comment]
docker-compose picks up changes in the build directory and auto-builds the image again, so for development, there's an argument for building with compose, but I assume in that case we would run the application locally anyways, so no, no good or strong reason for building in favor of downloading.

**Comment by weilbith** [comment]
I have good reasons for building the development version. It is called 'development', so I want to use it for development to test my stuff I'm just working on. Therefore it does not help me to work with an "old" version.
I'm not sure what @berndbohmeier is using at the moment for the end-to-end tests, but I could imagine that he maybe use this setup and then he requires to build the recent status.

Anyways, if the rest of them team argues for an image pull, according to our three different images (`bridge:latest` [equivalent to `bridge:release`], `bridge-next:master` and `bridge-next:pre-release`) I would go for the `master` build. This version should always contain all recent features that are done.

**Comment by schmir-at-bb** [comment]
As I said you can always build locally and tag the version the docker-compose file needs. Removing the build step is something I thought you would like to do, though it could be that I misinterpreted you.

What is the purpose of the docker-compose file?

**Comment by weilbith** [comment]
> What is the purpose of the docker-compose file?

I think this is a good question. Especially in relation to the usage with the quickstart script. We should have quick talk after the daily. I think this is more productive than these comments here.

**Comment by weilbith** [comment]
Input from meeting: Keep docker-compose as it is. 
Outstanding/running tests for `bridge/pre-release` and `bridge/release` branches.

**Comment by weilbith** [comment]
Note: Due to a GitHub outage (regarding PRs) this takes a while. The `bridge/pre-release` branch procedure was already successful. `bridge/release` is waiting to become triggered.
