### ISSUE TITLE
Make sure we compile the HomeBridge contract with optimizations turned on 

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/blockchain#318]
Check that we compile the home bridge contract with optimizations turned on with the bridge-deploy tool. It should be cheaper to deploy and it may make every confirmTransaction cheaper for the validators.

Please check that `test_measure_gas_home_bridge.py` also uses the same optimizer settings. We use that to determine the value to use for `bridge.constants.CONFIRMATION_TRANSACTION_GAS_LIMIT`

**Comment by schmir-at-bb** [comment]
If we do not compile with optimizations, we may even want to change the default in the contract-deploy-tools to compile with optimizations. I guess this is what we want in the general case.

**Comment by schmir-at-bb** [comment]
@weilbith Can you take care of that? I think you did most of the new bridge-deploy tool.

**Comment by weilbith** [comment]
Sure. I'll take this. How urgent is it? (current test deployment is done, correct?)

**Comment by berndbohmeier** [comment]
Not urgent afaik, but needs to be done.

**Comment by weilbith** [comment]
The compilation of the contracts in this scenario happens within the `Makefile`. The CLI then only loads the JSONs from the `./build` directory. So I could simply add the `--optimize` parameter here. 
But I think the suggested solution to adjust the `deploy-tools` is better. So I would simply adjust the `optimized_option` default value and also the `compile_project` default parameter.

**Comment by weilbith** [comment]
Regarding the gas usage for the confirmations:
The `plugin` module of the `deploy-tools` which is used by all tests to deploy a contract (including the measurement ones), is using the optimization per default. So all measurements so far have an optimization with 500 runs included. I can confirm this with some tests where I en-/disabled the optimization. Thereby the current variable value still holds. But the difference due to optimization regarding the optimization is marginal in comparison to how big the buffer is.

| | without optimization | with optimization (500 runs) |
|:---:|:---:|:---:|
| deploy | `1_041_914` | `728_751` |
| first confirmation | `118_465` | `117_427` |
| middle confirmation | `188_465` | `87_427` |
| last confirmation (50 validator) | `208_862` | `202_862` |
| last confirmation (123 validator) | `334_181` | `321_114` |
| after confirmation | `31_092` | `30_747` |

All values equal for 50 or 123 validators except the last confirmation.

**Comment by weilbith** [comment]
The last open point is to release a new version of the `deploy-tools` and update the constraints file.

**Comment by schmir-at-bb** [comment]
Thanks for the evaluation. This makes me wonder why is there such a drop in gas usage compared to the first and last confirmation.

We already have a new release and use that in the blockchain repo, which means we should also update it everywhere else in the constraints.txt file. @weilbith: Can you take care of that please? Feel free to merge without review if CI still succeeds. I have optimistically approved all of them now.

**Comment by berndbohmeier** [comment]
What do you mean by confirmation? a bid?

**Comment by weilbith** [comment]
Issue for updating: trustlines-network/project#631
