### ISSUE TITLE
Make bridge transfer complete even if the TLC transfer failed

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#392]
If the TLC transfer failed on the home chain (for example the contract there consumed too much gas) the transfer should still be confirmed. For that we add a flag (successful: true/false) to the TransferCompleted event. We should provide a fixed amount of gas for the value transfer (how much is up for discussion. example: just enough to emit a Log).

**Comment by schmir-at-bb** [comment]
see https://fravoll.github.io/solidity-patterns/secure_ether_transfer.html for different ways to send eth.

**Comment by schmir-at-bb** [comment]
So, it looks like we may end up with calling `receiver.call.value(_amount).gas(GAS)()`. We should make sure that this reverts the transaction if there is less than GAS gas left. If it would return false and the transaction completes successfully, validators could prevent transfers from getting handled by providing not enough gas. 

Regarding the flag in the TransferCompletedEvent, I think it would make sense to consider having a second event for 'value transfer succeeded`.

We could also let the user provide as much gas as he likes when we implement #389 (stuck transfers) in order to still complete the value transfer given enough confirmations have been sent.

(I still do think this is a terrible solution and we should not touch the contracts at all at this point).

**Comment by schmir-at-bb** [comment]
I've added a test that demonstrates that a transfer succeeds in one case and fails in another only based on the amount of gas the caller has provided even though the transaction itself succeeds.

This is exactly what we don't want to happen.

The problem seems to be that the `recipient.call.value(..).gas(...)("")` calls never reverts even though we have given a gasLimit to this call that greater than the initially provided gas, i.e. it doesn't check if enough gas is available.

This could also only be a problem in eth_tester. I didn't try to do the same with a real chain.

**Comment by schmir-at-bb** [comment]
That means we have to manually check that' there's enough gas with the `gasleft()` function.

@berndbohmeier , @jannikluhn  or is there a better way to do that?

**Comment by jannikluhn** [comment]
> The problem seems to be that the recipient.call.value(..).gas(...)("") calls never reverts even though we have given a gasLimit to this call that greater than the initially provided gas, i.e. it doesn't check if enough gas is available.

Oh, no... This is surprising to me and arguably a bug in Solidity? I doubt it's related to `eth_tester`.

I don't think there's a better way than checking `gasleft` as you suggest, either before or after the call.
