### ISSUE TITLE
Run equivocating validator

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#426]
Get a private validator to equivocate by running it twice or more on the same chain.

Use different coinbase addresses in the `user-config.toml` or using command-line arg.

Use DO 7, 8, and 9, or local machines.

Wait for tlbc-monitors to be running before starting this.

**Comment by jannikluhn** [comment]
Three validator nodes with the same private key are running on docker instances 0 with 2. They each use different `extra-data` so that the produced blocks are different. They have a low number of peers to increase block propagation time to them (I have not verified if this works though). I started them with the following command as I didn't find another way to pass CLI arguments to parity (or change the config file):

```
docker run -d -p 30300:30300 -p 30300:30300/udp -v /root/trustlines/databases:/data -v /root/trustlines/config:/config/custom -v /root/trustlines/enode:/config/network -v /root/trustlines/shared:/shared/ --network quickstart_laika-testnet trustlines/tlbc-testnet --role "validator" --address "2aeab6d45754831f88670eb28e86861bb7ba7de2" -p --extra-data="equivocator0" --max-peers=3
```

(Un)Fortunately, I have not observed an equivocation. The nodes seem to notice that there is another node that has already produced a block and refuse to create another one. All of them show the following log message during their slot, with timestamp exact to the second:

```
2019-09-30 14:56:00 UTC Attempted to seal block on the same step as parent. Is this authority sealing with more than one node?
```

A monitor on another node doesn't show an equivocation report.

Next steps:

- keep it running over night. Maybe we're lucky and something happens
- try to simulate high latency
- stop fourth privately run node

**Comment by jannikluhn** [comment]
After the fourth node has been shut down, some equivocations have been observed by at least one other node. Therefore, I have shut down the three validator nodes.

**Comment by berndbohmeier** [comment]
Done
