### ISSUE TITLE
Ensure that all images installed by the quickstart will be updated

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#441]
We should ensure that all images downloaded and started by the quickstart script, will be updated by watchtower. For this we need to use a tag that we will update.

**Comment by berndbohmeier** [comment]
Currently the updating is broken, because the api version used by watchtower (1.24) is not enough for the features we use like grace period(1.25)

**Comment by weilbith** [comment]
**What have I done:**
- setup the machine for a validator node with the quickstart script
- wait until both nodes have fully synced
- verify that netstats, monitor and bridge run fine:
  - the netstats client successfully reports and is shown as online on the webpage
  - the monitor gets fully synced, reporting offline validators from the past, he catches up syncing all the time
  - I run without actual validator privileges, so the bridge got into the stage that it theoretically schedules transfers, but warn me that I'm not a validator and have also not enough ETH to confirm transfers, I consider this running state as running fine
- I shut the network down with the exported `docker-compose` configuration
- I build the parity node image on my own and uploaded into a custom _DockerHub_ repository
- I adjusted the `trustlines-node` service to use this image instead of the original one
- I restarted the whole network and verify that all services run well
- I changed the parity config and build a new image version with it, that I pushed
- I waited for `watchtower` to update the trustlines node

**Result:**
- the bridge client remains stable, reporting that it can't connect to the trustlines node, but reconnects after a while
- the netstats crashes due to the missing connection, but the container restarts and after a while it works again
- the monitor crashes due to the missing connection, but the container restarts and after a while it works again

---

 I would call this a success. @berndbohmeier what is your opinion? Closable?

**Comment by berndbohmeier** [comment]
I would open issues to fix at least the monitor and maybe also the netstats. They should not crash. 
But yeah, overall it is a success. 
Close it after you created the two tasks.

**Comment by weilbith** [comment]
Issues have been created. :+1:

**Comment by weilbith** [comment]
So, let me clarify the confusion here:

This issue was mixed with #442. So the results commented here are actually the solution for the former issue. Thereby I will close #442. 
The introduction of the to update tasks is handled in PR #488. So I will not reopen this issue here, to avoid even more confusion.
