### ISSUE TITLE
Test/Fix documented way of equivocation reporting

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#445]
in https://github.com/trustlines-protocol/blockchain/issues/429 it was discovered that the documented workflow does not fully work.

**Comment by weilbith** [comment]
I think I found an issue. @jannikluhn did you used the command `report-via-file`?
Because I discovered that the documentation and the `Dockerfile` are not conform. The volume for the reports differs. So we should either fix the documentation or create a symbolic link in the _Docker_ image to the documented shorter path (`/opt/tlbc-monitor/reports` vs. `/reports`).

**Comment by weilbith** [comment]
In the conversation with Jannik it turns out that the connection to the _Parity_ node is the problem. It is likely that the user starts a node with the `quickstart` tool. The documented way how to report a validator does not fit for this scenario. Rather it is doing an assumption, which does not get elucidated to give the user a change to adopt. Thereby I will extend the `README` to tackle this problem. After all there is not **that** solution and it depends on the setup of the user.
