### ISSUE TITLE
Set docker-api version for watchtower

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#461]
Set the docker api version for the watchtower to at least 1.25 to allow using grace period. We should check that this actually works and also check if that would work with the default docker installation of the latest ubuntu. 
Document the new requirement.

**Comment by weilbith** [comment]
It seems like `v2tec` has renamed themselves to `containerrr`. The `v2tec` _DockerHub_ repository points to the _GitHub_ repository of `containerrr/watchtower`. Moreover has this image not been updated since 2 years. The new repository seems to be actively maintained. I have done my tests with the new repository. Thereby I will also switch the repository, in addition to define the CLI parameter.
