### ISSUE TITLE
Deploy bridge contracts

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/blockchain#9]
Deploy bridge contracts on both chains. 
Deploy ERC20 token on main chain.

**Comment by jannikluhn** [comment]
I've started with this, but didn't make much progress. Here's the current state for anyone who'd like to take over:

We need to deploy the following contracts:
- https://github.com/poanetwork/poa-network-consensus-contracts/blob/862c6e7b48f7a803e0282f05e90287b70b32af2a/contracts/RewardByBlock.sol
- ERC->native from https://github.com/poanetwork/poa-bridge-contracts

I've cloned the two repositories to the server. Running `npm install` in the consensus contracts repository fails and I haven't been able to fix it. When compilation is successful, we need to add the reward contract constructor to the side chain genesis file in `/root/chains/side_chain_spec.json` and redeploy the sidechain (by stopping the docker containers `node_side_1/2`, deleting the `chains` directory in `/root/chains/side_1/2` and restarting the containers again).

Deploying the bridge contracts also doesn't work for some reason. I tried both the dockerized and the undockerized ways described in the readme. In both cases I get the error message `Error: Error: Invalid JSON RPC response: ""` when the first RPC request is sent, even though I can send the same request manually and the URL ins configured properly. The config file `deploy/.env` should be filled in correctly, but the reward contract address is of course missing. The deployer address is funded on both chains (but this needs to be done again if the side chain is redeployed).

All addresses, private keys, passwords, enodes, and contract addresses can be found in `/root/notes`. It would be nice if the file is kept up to date.

**Comment by saschagoebel** [comment]
The bridge contracts (and most other things using truffle) don't work with Node 10.x most of the time. I'll install Node 8.x via nvm and try again.
@schmir FYI

**Comment by saschagoebel** [comment]
After much back and forth, I managed to deploy the contracts and run a single validator on the provided DigitalOcean Droplet (https://github.com/trustlines-protocol/blockchain/issues/7)

- I had to install node 8.x, because the truffle stack does not work reliably with node 10.x

- Updated the chain specs to assign some initial gas to the accounts mentioned in the notes file. Not sure if this was really necessary, but it was one of the steps to deploy.

- Added the RewardByBlock contract (https://github.com/poanetwork/poa-network-consensus-contracts/blob/862c6e7b48f7a803e0282f05e90287b70b32af2a/contracts/RewardByBlock.sol) to the Sidechain chain spec. This could have been done via a normal deployment and later change of the chain spec (https://wiki.parity.io/Block-Reward-Contract.html), but in either case the valid authorities need to be hardcoded in this contract (https://github.com/poanetwork/poa-network-consensus-contracts/blob/862c6e7b48f7a803e0282f05e90287b70b32af2a/contracts/RewardByBlock.sol#L122). This needs to be changed to some consensus mechanism, otherwise all validators could just print money 

- In *poa-bridge-contracts/deploy/.env*, the Foreign Limits and Gas can not simply be 0, because there are quite some checks in place (https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol#L24) when initializing the bridge on deployment.

- The Block Reward Contract needs to exist when deploying the bridge (https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol#L47), which is kind of a circular dependency, because the only one being able to mint coins should be the bridge contract on the home network.

- The token bridge docker-compose stack (https://github.com/poanetwork/token-bridge/blob/master/docker-compose.yml) does not work out of the box because of connectivity errors between the containers. Running Redis, RabbitMQ and the 5 Node Services manually worked though   
  ```bash
  docker run --volume "/root/bridges/main/token-bridge/bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia" --rm -d --name rabbitmq -p "0.0.0.0:4369:4369" -p "0.0.0.0:5671:5671" -p "0.0.0.0:5672:5672" -p "0.0.0.0:25672:25672" rabbitmq:3
  docker run --volume "/root/bridges/main/token-bridge/bridge_data/redis:/data" --rm -d --name redis -p "0.0.0.0:6379:6379" redis:4 redis-server --appendonly 'yes'
  npm run watcher:signature-request
  npm run watcher:collected-signatures
  npm run watcher:affirmation-request
  npm run sender:home
  npm run sender:foreign```

- The provided test scripts (https://github.com/poanetwork/token-bridge/tree/master/scripts/erc20_to_native) did not work and I gave up at this point.
